export default {
    BannerImg: require('../assets/Images/BannerImg.png'),
    InfoIcon: require('../assets/Images/InfoIcon.png'),
    Clock: require('../assets/Images/Clock.png'),
    Players: require('../assets/Images/Players.png'),
    ViewChart: require('../assets/Images/ViewChart.png'),
    ProfileImg: require('../assets/Images/ProfileImg.png'),
    Star: require('../assets/Images/Star.png'),
    UpArrow: require('../assets/Images/upArrow.png'),
    DownArrow: require('../assets/Images/downArrow.png'),
    ListImage: require('../assets/Images/ListImage.png'),
    Logo: require('../assets/Images/logo.png'),
    Message: require('../assets/Images/message.png'),
    Home: require('../assets/Images/Home.png'),
    Profile: require('../assets/Images/Profile.png'),
    Search: require('../assets/Images/Search.png'),
    Trophy: require('../assets/Images/Trophy.png'),
    LeaderBoard: require('../assets/Images/LeaderBoard.png'),
}